/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as MovieMovieIdRoute } from './routes/movie.$movieId'
import { Route as WishlistRoute } from './routes/wishlist'

// Create/Update Routes

const IndexRouteWithParent = IndexRoute.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MovieMovieIdRouteWithParent = MovieMovieIdRoute.update({
  path: '/movie/$movieId',
  getParentRoute: () => rootRoute,
} as any)

const WishlistRouteWithParent = WishlistRoute.update({
  path: '/wishlist',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteWithParent
      parentRoute: typeof rootRoute
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteWithParent
      parentRoute: typeof rootRoute
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteWithParent
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute: IndexRouteWithParent,
  MovieMovieIdRoute: MovieMovieIdRouteWithParent,
  WishlistRoute: WishlistRouteWithParent,
})

/* prettier-ignore-end */
